
package com.webserv.soap.score;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ScoreSOAPService", targetNamespace = "http://score.soap.webserv.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ScoreSOAPService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.webserv.soap.score.Score
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFirstScoreForGame", targetNamespace = "http://score.soap.webserv.com/", className = "com.webserv.soap.score.GetFirstScoreForGame")
    @ResponseWrapper(localName = "getFirstScoreForGameResponse", targetNamespace = "http://score.soap.webserv.com/", className = "com.webserv.soap.score.GetFirstScoreForGameResponse")
    public Score getFirstScoreForGame(
			@WebParam(name = "arg0", targetNamespace = "")
			Game arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.webserv.soap.score.Score>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllScores", targetNamespace = "http://score.soap.webserv.com/", className = "com.webserv.soap.score.GetAllScores")
    @ResponseWrapper(localName = "getAllScoresResponse", targetNamespace = "http://score.soap.webserv.com/", className = "com.webserv.soap.score.GetAllScoresResponse")
    public List<Score> getAllScores();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.webserv.soap.score.Score>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getScoresOver", targetNamespace = "http://score.soap.webserv.com/", className = "com.webserv.soap.score.GetScoresOver")
    @ResponseWrapper(localName = "getScoresOverResponse", targetNamespace = "http://score.soap.webserv.com/", className = "com.webserv.soap.score.GetScoresOverResponse")
    public List<Score> getScoresOver(
			@WebParam(name = "arg0", targetNamespace = "")
			long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.webserv.soap.score.Person
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersonByNick", targetNamespace = "http://score.soap.webserv.com/", className = "com.webserv.soap.score.GetPersonByNick")
    @ResponseWrapper(localName = "getPersonByNickResponse", targetNamespace = "http://score.soap.webserv.com/", className = "com.webserv.soap.score.GetPersonByNickResponse")
    public Person getPersonByNick(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0);

}
