
package com.webserv.soap.score;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ScoreSOAPService", targetNamespace = "http://score.soap.webserv.com/", wsdlLocation = "http://isimion-wstraining.rhcloud.com/isimion/ScoreSOAPService?wsdl")
public class ScoreSOAPService_Service
    extends Service
{

    private final static URL SCORESOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException SCORESOAPSERVICE_EXCEPTION;
    private final static QName SCORESOAPSERVICE_QNAME = new QName("http://score.soap.webserv.com/", "ScoreSOAPService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://isimion-wstraining.rhcloud.com/isimion/ScoreSOAPService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SCORESOAPSERVICE_WSDL_LOCATION = url;
        SCORESOAPSERVICE_EXCEPTION = e;
    }

    public ScoreSOAPService_Service() {
        super(__getWsdlLocation(), SCORESOAPSERVICE_QNAME);
    }

    public ScoreSOAPService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SCORESOAPSERVICE_QNAME, features);
    }

    public ScoreSOAPService_Service(URL wsdlLocation) {
        super(wsdlLocation, SCORESOAPSERVICE_QNAME);
    }

    public ScoreSOAPService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SCORESOAPSERVICE_QNAME, features);
    }

    public ScoreSOAPService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScoreSOAPService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ScoreSOAPService
     */
    @WebEndpoint(name = "ScoreSOAPService")
    public ScoreSOAPService getScoreSOAPService() {
        return super.getPort(new QName("http://score.soap.webserv.com/", "ScoreSOAPService"), ScoreSOAPService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ScoreSOAPService
     */
    @WebEndpoint(name = "ScoreSOAPService")
    public ScoreSOAPService getScoreSOAPService(WebServiceFeature... features) {
        return super.getPort(new QName("http://score.soap.webserv.com/", "ScoreSOAPService"), ScoreSOAPService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SCORESOAPSERVICE_EXCEPTION!= null) {
            throw SCORESOAPSERVICE_EXCEPTION;
        }
        return SCORESOAPSERVICE_WSDL_LOCATION;
    }

}
